stages:          # List of stages for jobs, and their order of execution
#  - build
  - test
#  - deploy

#build-job:       # This job runs in the build stage, which runs first.
#  stage: build
#  script:
#    - echo "Compiling the code..."
#    - echo "Compile complete."

unit-test:
  image: docker:cli
  tags:
    - shell
  stage: test
  before_script:
    - uname -a
    - chmod +x run_unit_test.sh
    - chmod +x ci-cd/python-init.sh
    - ls
    - pwd
  script:
    - /bin/sh run_unit_test.sh
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  # artifacts:
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: coverage.xml

lint-job:
  image: python:3.12-bookworm
  stage: test
  tags:
    - docker
  before_script:
  - python3 --version ; pip3 --version
  - pip3 install -r requirements.txt
  script:
    - pylint src test


#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."


# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
