unit-test:
  image: docker:cli
  tags:
    - shell
  before_script:
    - uname -a
    - cd harvest-and-collect
    - chmod +x run_unit_test.sh
    - ls -l
    - pwd
  script:
    - /bin/sh run_unit_test.sh
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/

lint-job:
  image: python:3.12-bookworm
  allow_failure: true
  tags:
    - docker
  before_script:
    - uname -a
    - cd harvest-and-collect
    - python3 --version ; pip3 --version
    - pip3 install -r requirements.txt
  script:
    - pylint src test
