plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
  - -  "@semantic-release/git"
    - assets:
        - pom.xml
      message: "chore(release): bump ${nextRelease.version}"

branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"
