version: '3'
services:
  python:
    image: python:3.12
    container_name: python
    volumes:
      - ./src:/app/src:ro
      - ./test:/app/test:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./ci-cd/python-init.sh:/app/python-init.sh:ro
      - ./mock-response:/app/mock-response:ro
    depends_on:
      - neo4j
    entrypoint: [ "./app/python-init.sh" ]
  neo4j:
    image: neo4j:5.15.0-community-bullseye
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_AUTH: none
    logging:
      driver: none
